### ISSUE TITLE
The Amplify CLI can NOT find command

### ISSUE THREAD

**Issue by aluminick** [hatertron3000/amplify-bigcommerce#10]
when I ran `amplify serve` i'm getting `The Amplify CLI can NOT find command:  serve` error.

**Comment by hatertron3000** [comment]
Hey @aluminick - thanks for the report. This sounds like it's more of an issue with the Amplify CLI or the local configuration than then an issue with the example BC app here, so your issue here will probably be the best one to follow: https://github.com/aws-amplify/amplify-cli/issues/2464

But, I've never seen that error so I got curious and checked it out. First I ran `amplify serve` myself in a directory was not initialized as an Amplify project, but no, that's a different error.

On a hunch, I updated my Amplify CLI and did the same test. Boom, I get `The Amplify CLI can NOT find command:  serve`.

With a little extra digging, I found this PR that sounds like it should fix the issue once it's merged: https://github.com/aws-amplify/amplify-cli/pull/2394

Since this is an issue with the current version of Amplify CLI and not with this app, I am going to close your report here, but I'll keep a close eye on your report with AWS here: https://github.com/aws-amplify/amplify-cli/issues/2464

In the meantime, I suspect that installing an older version of Amplify CLI will allow you to continue until AWS is able to patch this problem in the current version. Thanks again for bringing this up, and I hope this sample app gives you a good starting place for your next BigCommerce project!
